# -*- coding: utf-8 -*-
"""CalculadoraPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n4L2Zm8i9Mmj_6HLo3jHQPiJfidK8pur
"""

while 1:
  print("------CALCULADORA------")
  print("POR FAVOR ELIJA LA OPERACION A REALIZAR")
  print("1. SUMA")
  print("2. RESTA")
  print("3. MULTIPLICACIÓN")
  print("4. DIVISIÓN")
  print("5. SALIR")

  op=int(input())

  if op==5:
    print("PROCESO FINALIZADO")
    break
  
  if op>5:
      print("DIGITE UNA OPCIÓN VALIDA")
      break

  num1=float(input("INGRESE EL PRIMER VALOR: "))
  num2=float(input("INGRESE EL SEGUNDO VALOR: "))
  if op==1:
    sum=num1+num2
    print("El resultado de la suma es: ", sum)
  elif op==2:
    rest=num1-num2
    print("El resultado de la resta es: ", rest)
  elif op==3:
      mult=num1*num2
      print("El resultado de la multiplicacion es: ", mult)
  elif op==4:
      div=num1/num2
      print("El resultado de la división es: ", div)